language: python

python:
  - '3.4'

env:
  - DJANGO_SETTINGS_MODULE=django_th.test_settings

install:
  - pip install -r requirements-all.txt

script:
  - python manage.py test -v2

deploy:
  provider: pypi
  user: foxmask
  password:
    secure: SMBRrjUZ2kngOV89YkMyIh8W21CGa+9l6cvlnBXhmmuTt/jlx4sT2HHSzmIFAAsGYkatGj66AVibVsUaqoch2kIH75IOgww38PSgHP4KuqsDIm7xWCcHPSZfXSC3hi89/RwSzFeHCapVXKTW+EKO6FS9hesG6pSMYVTF6WCXnoQ=
  on:
    tags: true
    repo: foxmask/django-th
